### ISSUE TITLE
🐞[BUG]: Error: You have forgotten to import the NGXS module!

### ISSUE THREAD

**Issue by martinsotirov** [ngxs/store#1729]
### Affected Package

@ngxs/store

### Is this a regression?

Don't know. First time I'm seeing it.

### Description

My server side rendered Angular 11 app exhibits a strange behavior where if I'm sending many concurrent requests (like via a benchmark or a SEO crawler), it would start throwing `ERROR Error: You have forgotten to import the NGXS module!` errors in some of my components that use my stores. If I'm just opening the page in the browser or sending a "slow" benchmark it works fine.

At first I thought it's because of my lazy loaded modular stores but then I reverted to an older commit with a monolith architecture and it exhibits the same behavior when multiple fast requests are hammering the app.

## 🔬 Minimal Reproduction

1. Install Angular and NGXS
2. Access an NGXS getter via `@Select()` in some component
3. Setup server side rendering with `nguniversal`
4. Send many concurrent requests for the page that accesses the NGXS store

## 🔥 Exception or Error
```
ERROR Error: You have forgotten to import the NGXS module!
    at createSelectObservable (/path/to/my/app/dist/my-app/server/main.js:159278:15)
    at GuideCategoriesComponent.get [as categories$] (/path/to/my/app/dist/my-app/server/main.js:159349:68)
    at GuideCategoriesComponent_Template (/path/to/my/app/dist/my-app/server/main.js:255335:142)
    at executeTemplate (/path/to/my/app/dist/my-app/server/main.js:74219:9)
    at refreshView (/path/to/my/app/dist/my-app/server/main.js:74088:13)
    at refreshComponent (/path/to/my/app/dist/my-app/server/main.js:75254:13)
    at refreshChildComponents (/path/to/my/app/dist/my-app/server/main.js:73885:9)
    at refreshView (/path/to/my/app/dist/my-app/server/main.js:74138:13)
    at refreshEmbeddedViews (/path/to/my/app/dist/my-app/server/main.js:75208:17)
    at refreshView (/path/to/my/app/dist/my-app/server/main.js:74112:9)

ERROR Error: You have forgotten to import the NGXS module!
    at createSelectObservable (/path/to/my/app/dist/my-app/server/main.js:159278:15)
    at GuidePostComponent.get [as categories$] (/path/to/my/app/dist/my-app/server/main.js:159349:68)
    at GuidePostComponent.get postCategory$ [as postCategory$] (/path/to/my/app/dist/my-app/server/main.js:258896:81)
    at GuidePostComponent_div_0_Template (/path/to/my/app/dist/my-app/server/main.js:258857:154)
    at executeTemplate (/path/to/my/app/dist/my-app/server/main.js:74219:9)
    at refreshView (/path/to/my/app/dist/my-app/server/main.js:74088:13)
    at refreshEmbeddedViews (/path/to/my/app/dist/my-app/server/main.js:75208:17)
    at refreshView (/path/to/my/app/dist/my-app/server/main.js:74112:9)
    at refreshComponent (/path/to/my/app/dist/my-app/server/main.js:75254:13)
    at refreshChildComponents (/path/to/my/app/dist/my-app/server/main.js:73885:9)
```

## Environment

Libs:
- @angular/core version: 11.2.3
- @ngxs/store version: 3.7.1
- @nguniversal/common: 11.2.0
- @nguniversal/express-engine: 11.2.0

Browser:
- [x] Screaming Frog Spider Crawler version 14.3
- [x] Chrome (desktop) version 89.0.4389.90
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 85.0.2 
- [x] Safari (desktop) version  14.0.3
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.4.0
- Platform: macOS 11.2.2

**Comment by martinsotirov** [comment]
Seems like I created a duplicate of #1723. My bad. I guess this one can be closed.

**Comment by martinsotirov** [comment]
We decided that investing the time to refactor our app to NgRx is worth it after all, seeing as this bug isn't a high priority for ngxs.

**Comment by iangellaco** [comment]
anyone solve this issue already ?

**Comment by PiyushAgrawal1243** [comment]
I am facing the same issue if anyone knows the solution please help.

Thanks

**Comment by ryarasi** [comment]
Facing the same issue, even after upgrading to 3.7.4

**Comment by vinwiz** [comment]
> Facing the same issue, even after upgrading to 3.7.4

 Facing the same issue

**Comment by fadingbeat** [comment]
I am facing this issue with Jest testing. I imported the NgxsModule with state list, and still get this error. This was not the case in my previous tests.

**Comment by webia1** [comment]
Same here; it happens every once in a while.

**Comment by MaximeKoitsalu** [comment]
Facing the same issue here as well :S

**Comment by webia1** [comment]
Understanding question: Did you try the solution above, and it still did not work?

**Comment by MaximeKoitsalu** [comment]
Thanks for the reply, it turned out to be an issue with pathMapping in angular.json. Using explicit imports and avoiding shortened imports solved the underlying issue for my team.

**Comment by myszkin81** [comment]
I am still facing this issue.
Replacing @Select with this.store.select() didn't help.
Anyone still has this problem? This happens on SSR
