### ISSUE TITLE
🐞[BUG]: Many errors in SSR

### ISSUE THREAD

**Issue by kaname-png** [ngxs/store#1813]
### Description

As far as I understand I have everything ok since using the ng serve command I don't get any error, but when I use ssr I get that error I don't know why.

## 🔥 Exception or Error
<pre><code>

ERROR Error: You have forgotten to import the NGXS module!
    at createSelectObservable (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:159178)
    at HeaderComponent.get [as clientState$] (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:160050)
    at HeaderComponent_ng_template_9_ng_container_1_Template (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:4597768)
    at executeTemplate (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:2197275)
    at refreshView (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:2194943)
    at refreshEmbeddedViews (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:2215609)
    at refreshView (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:2195412)
    at refreshEmbeddedViews (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:2215609)
    at refreshView (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:2195412)
    at refreshComponent (/home/container/naeko-dashboard/dist/naeko-dashboard/server/main.js:1:2216330)
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 13.1.0
- @ngxs/store version:3.7.3

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 14
- Platform:  Linux

**Comment by mgrahamama** [comment]
i am facing this same issue and with routeGuards and selectors with SSR

**Comment by splincode** [comment]
@markwhitfeld @arturovt what do you think about?

**Comment by pmankialevich** [comment]
Circular call actions in ssr
action [Forms] Update Form Value -> action [Forms] Update Form Dirty -> action [Forms] Update Form Errors ->

**Comment by arturovt** [comment]
This has been fixed as part of the [v3.7.4](https://github.com/ngxs/store/releases/tag/v3.7.4) release.
Please test this out and let us know if this is not resolved.

**Note:** there's an issue unit tests, we're tracking it in a separate issue #1854 .
