### ISSUE TITLE
🐞[BUG]: Could not use NgxsFormPlugin in subModule on Federation Architecture

### ISSUE THREAD

**Issue by qq253498229** [ngxs/store#2074]
### Affected Package

I don't know.

### Is this a regression?

I don't know.

### Description

My application uses the Angular and Federation architecture, and I encountered this error when using the ngxs-form-plugin in a child module:

```
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(PlayfabModule)[FormGroupDirective -> FormGroupDirective -> FormGroupDirective]: 
  NullInjectorError: No provider for FormGroupDirective!
NullInjectorError: R3InjectorError(PlayfabModule)[FormGroupDirective -> FormGroupDirective -> FormGroupDirective]: 
  NullInjectorError: No provider for FormGroupDirective!
    at NullInjector.get (core.mjs:8890:27)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at ChainedInjector.get (core.mjs:14018:36)
    at lookupTokenUsingModuleInjector (core.mjs:4608:39)
    at getOrCreateInjectable (core.mjs:4656:12)
    at Module.ɵɵdirectiveInject (core.mjs:11801:19)
    at NodeInjectorFactory.FormDirective_Factory [as factory] (ngxs-form-plugin.js:149:120)
    at getNodeInjectable (core.mjs:4862:44)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11070:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
```

The HTML looks like this:

```
  <form nz-form [formGroup]="validateForm" class="login-form" (ngSubmit)="submitForm()"
        ngxsForm="playfab.form">
  .......
```

If I remove `ngxsForm="playfab.form"` , the page works correctly. However, when I add it, I get that error.

In my child module, I imported the following modules:

```
CommonModule,
FormsModule,
ReactiveFormsModule,
RouterModule.forChild(routes),
NgxsModule.forFeature([PlayfabState]),
NgxsFormPluginModule,
```

I also imported some related `ng-zorro-antd` modules. 

I'm not sure if this import setup is correct, and I'm trying to identify which modules might be causing the exception with the formPlugin.

## 🔬 Minimal Reproduction

https://github.com/qq253498229/error003.git

## 🔥 Exception or Error
<pre><code>

ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(PlayfabModule)[FormGroupDirective -> FormGroupDirective -> FormGroupDirective]: 
  NullInjectorError: No provider for FormGroupDirective!
NullInjectorError: R3InjectorError(PlayfabModule)[FormGroupDirective -> FormGroupDirective -> FormGroupDirective]: 
  NullInjectorError: No provider for FormGroupDirective!
    at NullInjector.get (core.mjs:8890:27)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at ChainedInjector.get (core.mjs:14018:36)
    at lookupTokenUsingModuleInjector (core.mjs:4608:39)
    at getOrCreateInjectable (core.mjs:4656:12)
    at Module.ɵɵdirectiveInject (core.mjs:11801:19)
    at NodeInjectorFactory.FormDirective_Factory [as factory] (ngxs-form-plugin.js:149:120)
    at getNodeInjectable (core.mjs:4862:44)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11070:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
handleError @ core.mjs:10614
next @ core.mjs:28366
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
emit @ core.mjs:10670
(anonymous) @ core.mjs:11109
invoke @ zone.js:368
run @ zone.js:129
runOutsideAngular @ core.mjs:10979
onHandleError @ core.mjs:11109
handleError @ zone.js:372
runGuarded @ zone.js:142
api.microtaskDrainDone @ zone.js:1054
drainMicroTaskQueue @ zone.js:588
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
scheduleTask @ zone.js:392
onScheduleTask @ core.mjs:10752
scheduleTask @ zone.js:382
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:216
scheduleMicroTask @ zone.js:236
scheduleResolveOrReject @ zone.js:1247
resolvePromise @ zone.js:1184
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
webpackJsonpCallback @ jsonp chunk loading:77
(anonymous) @ projects_plugin-playfab_src_app_modules_playfab_playfab_module_ts.js:1
Show 32 more frames
Show less

</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 16.0.0
- @ngxs/store version: 3.8.1
- @ngxs/form-plugin version: 3.8.1
- @angular-architects/module-federation: 16.0.4

Browser:
- [x] Chrome (desktop) version 118.0.5993.117
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v20.9.0  
- Platform:  macOS 13.6 (22G120) 

Others:

</code></pre>

**Comment by qq253498229** [comment]
I'm sorry, it seems to be my mistake. 

I rebuilt the project from scratch exactly as it was, and I found that it can run properly now. 

I'm not sure where the issue occurred, so I believe I should temporarily close this issue for now.
