### ISSUE TITLE
🐞[BUG]: Fresh Angular 18 project and NGXS docs / Cannot find module standalone.js

### ISSUE THREAD

**Issue by mhp-borisbojic** [ngxs/store#2183]
### Affected Package
@ngxs/store

### Description

Following the documentation (installation) leads to an error message

## 🔬 Minimal Reproduction

1. Create a fresh Angular 18 project: `ng new ng18test` with all default configuration / settings, no SSR
2. Switch to directory `cd ng18test`
3. Add @ngxs/store by docs: `ng add @ngxs/store`

## 🔥 Exception or Error

Adding @ngxs/store leads to:
<pre><code>
ℹ Using package manager: npm
✔ Found compatible package version: @ngxs/store@18.0.0.
✔ Package information loaded.

The package @ngxs/store@18.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Cannot find module '/Users/borisbojic/Development/ng18test/node_modules/@schematics/angular/private/standalone.js'
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: ^18.0.0
- @ngxs/store version: ^18.0.0
 
For Tooling issues:
- node.js 20.15.0
- macOS 14.5

**Comment by msmallest** [comment]
Same issue as well when trying to use a schematic for initializing a store in a project

**Comment by mhp-borisbojic** [comment]
Sadly, it only fixed the error message, but it still doesn't work as expected - I've deleted node_modules and yarn.lock as well:

```
❯ ng add @ngxs/store
ℹ Using package manager: yarn
✔ Found compatible package version: @ngxs/store@18.0.0.
✔ Package information loaded.

The package @ngxs/store@18.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Collection "@ngxs/store" cannot be resolved.
❯ yarn
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 251ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 433ms
❯ ng generate @ngxs/store:starter-kit
An unhandled exception occurred: Collection "@ngxs/store" cannot be resolved.
See "/private/var/folders/jd/5j65z2j12ql0c1bkp5jlz3qc0000gp/T/ng-ma6wHT/angular-errors.log" for further details.
```

The content of the log:

```
[error] Error: Collection "@ngxs/store" cannot be resolved.
    at SchematicEngineHost.resolve (/opt/homebrew/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:86:19)
    at SchematicEngineHost._resolveCollectionPath (/opt/homebrew/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:91:37)
    at SchematicEngineHost.createCollectionDescription (/opt/homebrew/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:116:27)
    at SchematicEngine._createCollectionDescription (/opt/homebrew/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:167:40)
    at SchematicEngine.createCollection (/opt/homebrew/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:160:43)
    at GenerateCommandModule.getSchematics (/opt/homebrew/lib/node_modules/@angular/cli/src/commands/generate/cli.js:137:48)
    at async GenerateCommandModule.getSchematicsToRegister (/opt/homebrew/lib/node_modules/@angular/cli/src/commands/generate/cli.js:177:76)
    at async GenerateCommandModule.builder (/opt/homebrew/lib/node_modules/@angular/cli/src/commands/generate/cli.js:33:55)
    at async runCommand (/opt/homebrew/lib/node_modules/@angular/cli/src/command-builder/command-runner.js:76:5)
    at async default_1 (/opt/homebrew/lib/node_modules/@angular/cli/lib/cli/index.js:70:16)
```

**Comment by markwhitfeld** [comment]
@mhp-borisbojic The fix has been merged, but not released yet. It will be released soon.
If you want to try out the unreleased version you can use the `@ngxs/store@dev` package.

**Comment by markwhitfeld** [comment]
@mhp-borisbojic v18.1.0 has been released, and includes a fix for this issue. 🎉

**Comment by mhp-borisbojic** [comment]
Thanks, it works now! :)
