### ISSUE TITLE
Can't resolve all parameters for StateFactory: (?, ?).

### ISSUE THREAD

**Issue by junimohano** [ngxs/store#464]
Can't run example app (https://github.com/ngxs/store/tree/master/integration)

Do I need to do something else ?

`Error: Can't resolve all parameters for StateFactory: (?, ?).
compiler.js:215
    at syntaxError (http://localhost:4200/vendor.js:5960:17)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.js:16552:35)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.js:16445:26)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getInjectableTypeMetadata (http://localhost:4200/vendor.js:16667:21)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.js:16676:22)
    at http://localhost:4200/vendor.js:16614:49
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.js:16574:19)
    at http://localhost:4200/vendor.js:16197:118
    at Array.forEach (<anonymous>)
Error: Can't resolve all parameters for StateFactory: (?, ?).
compiler.js:215
    at syntaxError (http://localhost:4200/vendor.js:5960:17)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.js:16552:35)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.js:16445:26)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getInjectableTypeMetadata (http://localhost:4200/vendor.js:16667:21)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.js:16676:22)
    at http://localhost:4200/vendor.js:16614:49
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.js:16574:19)
    at http://localhost:4200/vendor.js:16197:118
    at Array.forEach (<anonymous>)`

**Comment by amcdnl** [comment]
Please fill out the issue template and provide repo cases. Feel free to reopen when you can give us more info.

**Comment by sanjibani** [comment]
I'm getting the same issue. But i didn't understand the comment
"Please fill out the issue template and provide repo cases. Feel free to reopen when you can give us more info"
Please explain

**Comment by deebloo** [comment]
@salomoni when you create an issue on github it asks you to provide several pieces of information that are necessary for us to help you solve your issue

**Comment by salomoni** [comment]
@deebloo I don't quite follow, what's up?

**Comment by jtomek** [comment]
Did you just upgrade to Angular 8? I'm getting a similar problem: Can't resolve all parameters for LoginComponent: (?, ?, ?)

**Comment by splincode** [comment]
@jtomek We can't reproduce, please create new issue if you have some problem

**Comment by gradzio** [comment]
@junimohano the solution is to add @Injectable() after @State decorator in your state. It fixed my errors after upgrading to angular 9

**Comment by cahitbeyaz** [comment]
Thanks @gradzio adding `@Injectable()` after `@State ` solved problem
