### ISSUE TITLE
Can't build production when using documented dynamic selectors

### ISSUE THREAD

**Issue by kayvanbree** [ngxs/store#762]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using a dynamic selector, the Angular compiler will complain about using Lambda function within a static function. It won't compile if you follow the documentation:
```
static pandas(type: string) {
    return createSelector([ZooState], (state: string[]) => {
      return state.filter(s => s.indexOf('panda') > -1)
                  .filter(s => s.indexOf(type) > -1);
    });
  }
```

## Expected behavior

I found out that adding `// @dynamic` above the class will let the Angular compiler ignore this warning, however I don't know if this is the correct way to deal with this problem. 
```
// @dynamic
@State<string[]>({
  name: 'animals',
  defaults: []
})
export class ZooState {
  static pandas(type: string) {
    return createSelector([ZooState], (state: string[]) => {
      return state.filter(s => s.indexOf('panda') > -1)
                  .filter(s => s.indexOf(type) > -1);
    });
  }
}
```
I would like to see the documentation updated to include something about this problem. This could either be telling people to add `// @dynamic` to the class,  or anything else if you guys have a better solution.

## What is the motivation / use case for changing the behavior?

I tried to build my library that I am refactoring to use NGXS. I couldn't find this problem on this repository nor on the website, but I think it should be addressed somewhere.

## Environment

<pre><code>
Libs:

```
    "@angular/core": "^6.0.3",
    "@ngxs/devtools-plugin": "^3.3.4",
    "@ngxs/store": "^3.3.4",
```

**Comment by splincode** [comment]
Add repo for reproduce

**Comment by kayvanbree** [comment]
We use a private SVN repo... :(

I'll create one to demo it.

**Comment by kayvanbree** [comment]
Looks like it only happens when you use it in a library. 

You can find a reproduction at https://github.com/kayvanbree/ngxs-dynamic-selector-build-error, with the branch 'fixed' containing the `// @dynamic`, which counters the problem.

Here's the build error:

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run build:prod --scripts-prepend-node-path=auto

> dynamic-selector-build-error@0.0.0 build:prod C:\Projects\eigen\dynamic-selector-build-error
> ng build zoostate

Building Angular Package

BUILD ERROR
C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:3:1: Error encountered in metadata generated for exported symbol 'ZooState': 
 C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:15:25: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":14,"character":24}
Error: C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:3:1: Error encountered in metadata generated for exported symbol 'ZooState': 
 C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:15:25: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":14,"character":24}
    at C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:708:31
    at Array.forEach (<anonymous>)
    at validateMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:696:46)
    at MetadataCollector.getMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:551:21)
    at MetadataCache.getMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\metadata_cache.js:87:41)
    at Object.getSourceFileMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:117:56)
    at Object.readMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:46:37)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:469:38)
    at StaticSymbolResolver.getModuleMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler\bundles\compiler.umd.js:22867:49)
    at StaticSymbolResolver._createSymbolsOf (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler\bundles\compiler.umd.js:22658:33)

C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:3:1: Error encountered in metadata generated for exported symbol 'ZooState': 
 C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:15:25: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":14,"character":24}
Error: C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:3:1: Error encountered in metadata generated for exported symbol 'ZooState': 
 C:/Projects/eigen/dynamic-selector-build-error/projects/zoostate/src/lib/zoo.state.ts:15:25: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":14,"character":24}
    at C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:708:31
    at Array.forEach (<anonymous>)
    at validateMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:696:46)
    at MetadataCollector.getMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:551:21)
    at MetadataCache.getMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\metadata_cache.js:87:41)
    at Object.getSourceFileMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:117:56)
    at Object.readMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:46:37)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:469:38)
    at StaticSymbolResolver.getModuleMetadata (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler\bundles\compiler.umd.js:22867:49)
    at StaticSymbolResolver._createSymbolsOf (C:\Projects\eigen\dynamic-selector-build-error\node_modules\@angular\compiler\bundles\compiler.umd.js:22658:33)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dynamic-selector-build-error@0.0.0 build:prod: `ng build zoostate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dynamic-selector-build-error@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kvbree\AppData\Roaming\npm-cache\_logs\2019-01-11T12_48_13_113Z-debug.log

Process finished with exit code 1
```

**Comment by splincode** [comment]
This is related to your setting of strictMetadataEmit. If you set this to false this error will disappear.

**Comment by kayvanbree** [comment]
These are standard settings for Angular. I doubt they made it this way for no reason. What will be the implications of setting strictMetadataEmit to false?

**Comment by arturovt** [comment]
@kayvanbree You can suppress this error by including `@dynamic` comment.

```TS
// @dynamic
@State<string[]>({
    name: 'animals',
    defaults: []
})
export class ZooState {
    static pandas(type: string) {
        return createSelector([ZooState], (state: string[]) => {
            return state.filter(s => s.indexOf('panda') > -1)
                        .filter(s => s.indexOf(type) > -1);
        });
    }
}
```

[source](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/metadata/collector.ts#L675)

**Comment by arturovt** [comment]
@kayvanbree Adding `@dynamic` comment is ok, this will not affect your code, until you are doing something really bad :smile: Angular docs also says `You can choose to suppress the error emitted by this option for an exported symbol by including @dynamic in the comment documenting the symbol.` Thus I guess it's a normal approach.

**Comment by splincode** [comment]
Docs updated

**Comment by Siddharth77** [comment]
Instead of doing below :
public static A(state, action) {
        return state.x.filter((a) =>
        !action.b.c.some((Z) => {
            if (a._id.$oid === Z._id.$oid) {
                 a.p.d= Z.p.d;
            }
        }));
    }
Do This:
public static A(state, action) {
        const data = state.x.filter((a) =>
        !action.b.c.some((Z) => {
            if (a._id.$oid === Z._id.$oid) {
                 a.p.d= Z.p.d;
            }
        }));
       return data;
    }
